CREATE TABLE `gcp-pde-344913.proj_estudo.movies` (
  id INTEGER,
  title STRING,
  overview STRING,
  release_date DATE,
  backdrop_path STRING,
  belongs_to_collection STRING,
  budget INTEGER,
  genres STRING,
  homepage STRING,
  imdb_id STRING,
  original_language STRING,
  original_title STRING,
  popularity FLOAT,
  poster_path STRING,
  production_companies STRING,
  production_countries STRING,
  revenue INTEGER,
  runtime INTEGER,
  spoken_languages STRING,
  status STRING,
  tagline STRING,
  video BOOLEAN,
  vote_average FLOAT,
  vote_count INTEGER
);
